version: '3.8'

services:
  shoppingdb:
    image: postgres
    environment:
      POSTGRES_USER: hse24
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shoppingdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    environment:
      DATABASE_URL: postgres://hse24:password@shoppingdb:5432/shoppingdb  
      PORT: 8080
    depends_on:
      - shoppingdb
    ports:
      - "8080:8080"  
    command: "node server.js" 

  frontend:
    image: maeddes/frontendflask:hse24
    build:
      context: ./frontend
    environment:
      API_URL: "http://backend:8080/api/shopping"
    ports:
      - "5000:5000"
    depends_on:
      - backend

volumes:
  db_data:
